services:
 mongodb:
  image: mongo
  restart: always
  volumes:
    - ./mongo/db/init:/docker-entrypoint-initdb.d/
    - ./mongo/db/shared:/shared
    - ./csv:/csv
  ports:
    - "27017:27017"
 mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9092:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/